IdeaRunShopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.authtoken import views
from rest_framework.schemas import get_schema_view
# from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Shopping'

schema_view = get_schema_view(title="Server Monitoring API", permission_classes=[])

urlpatterns = [
    # url(r'^(?P<filename>(robots.txt)|(humans.txt))$', home_files, name='home-files'),

    url(r'^api-auth/', views.obtain_auth_token),
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url('^$', schema_view),
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('Shopping.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += i18n_patterns(
#
# )

Shopping/urls.py
from django.conf.urls import url
from Shopping import views
app_name = 'shop'

urlpatterns = [

    url(r'^api-product-lists/', views.ApiProductList.as_view(), ),
    url(r'^api-my-orders/', views.ApiMyOrderList.as_view(), ),
    url(r'^api-signup/', views.ApiSignUpView.as_view(), ),
    url(r'^api-category-lists/', views.ApiCategoryList.as_view(), ),
    url(r'^api-category-product/', views.ApiCatProductList.as_view(), ),
    url(r'^api-search-product/', views.ApiSearchProduct.as_view(), ),

    url(r'^home', views.Index, name='homepage', ),
    url(r'^product-lists/(?P<pk>[0-9]+)/', views.ProductList.as_view(), name='productlist', ),
    url(r'^product-lists-detail/(?P<pk>[0-9]+)/', views.ProductListDetail,name='productdetail', ),
    url(r'^category-detail/(?P<pk>[0-9]+)/', views.CategoryDetail,name='categorydetail', ),
    url(r'^signup/', views.SignUp.as_view(), name='signup', ),
    url(r'^signin/', views.SignIn.as_view(), name='signin', ),
    url(r'^logout/', views.LogOut, name='logout', ),
    url(r'^categories/', views.Categories, name='categories', ),
    url(r'^myorders/', views.Orders.as_view(), name='myorders', ),
    url(r'^search/', views.search.as_view(), name='search')

    # url(r'^search-product/', views.SearchProduct.as_view(), ),
]

Shopping/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.utils.translation import gettext_lazy as _

# This code is triggered whenever a new user has been created and saved to the database
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class Category(models.Model):

    title = models.CharField(max_length=50, verbose_name=_('title of related category'))
    sold_price = models.IntegerField(default=0 , verbose_name=_('sold price'))
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('title'))
    price = models.IntegerField(verbose_name=_('price'))
    sold_price = models.IntegerField(default=0, verbose_name=_('sold price'))

    description = models.TextField(verbose_name=_('description'))
    # todo why not ImageField?
    # todo not "picture"? it's not like we're charged by characters used :D
    # using full words increases code readability
    pic = models.FileField(blank=True, verbose_name=_('picture'))
    # //todo we should always define the "related_name" for relational fields (fk, m2m).
    cat = models.ForeignKey(Category, related_name='category', verbose_name=_('Category'), on_delete= models.CASCADE)
    available = models.IntegerField(verbose_name=_('Available'))

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.title + " " + self.cat.title

    def cat_title(self):
        return self.cat.title


class NotAvProManager(models.Manager):
    def get_queryset(self):
        return super(NotAvProManager, self).get_queryset().filter(available=0)


class NotAvPro(Product):
    objects = NotAvProManager()
    class Meta:
        verbose_name = _('Not available product')
        verbose_name_plural=_('Not available products')
        proxy = True

    def __str__(self):
        return self.title


class Order(models.Model):

    STAT = (("P", "Pending"),
            ("D", "Done"),
            ("C", "Cancel"),
            ("H", "Handeling"))

    person = models.ForeignKey('auth.User', related_name='orders', verbose_name=_('Ordered person') , on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True, verbose_name=_('Date'))
    products = models.ManyToManyField(Product, verbose_name=_('orders products'))  # TODO a reD MANY TO MANAY DOC ANF ITS TABLE
    status = models.CharField(max_length=1, choices=STAT, default='P',verbose_name=_('Order status'))
    total_price = models.IntegerField(default=0, verbose_name=_('Order Price'))

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __init__(self, *args, **kwargs):
        super(Order, self).__init__(*args, **kwargs)
        self.__original_status = self.status

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.status == "D" and self.__original_status == "P":
            for p in (self.products.all()):
                p.available = p.available - 1
                p.sold_price = p.sold_price + p.price
                p.cat.sold_price = p.cat.sold_price + p.price
                cat = p.cat
                print(p.cat.title)
                cat.save()
                p.save()

        elif self.status == "C" and self.__original_status == "D":
            for p in (self.products.all()):
                p.available = p.available + 1
                p.sold_price = p.sold_price - p.price
                p.cat.sold_price = p.cat.sold_price - p.price
                cat = p.cat
                print(p.cat.title)
                cat.save()
                p.save()

        return super().save(force_insert=force_insert, force_update=force_update, *args, **kwargs)

Shopping/forms.py
from django.contrib.auth.models import User
from .models import Order, Product
from django import forms
from django.utils.translation import gettext_lazy as _

class UserForm ( forms.ModelForm ):
    password = forms.CharField(widget=forms.PasswordInput, label=_('password'))
    class Meta:#information about the class
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

class UserFormIn ( forms.Form ):
    username = forms.CharField(label =_('username'))
    password = forms.CharField(widget=forms.PasswordInput, label =_('password'))

class OrderForm (forms.ModelForm):
    # TODO multi choose from available products
    # products = forms.CharField(label=_('products'))
    products = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), queryset= Product.objects.filter(available__gt=0))

    class Meta:
        model = Order
        fields=['products', ]

    def save(self, commit=True):
        order = super(OrderForm, self).save(commit=False)
        for p in (order.products.all()):
            order.total_price = order.total_price + p.pricex
        print(order.total_price)
        order.save()

        return order


class SearchForm (forms.Form):
    category_title = forms.CharField(required=False,label=_('Category'))
    product_title = forms.CharField(required=False, label=_('Product'))

Shopping/views.py
from django.shortcuts import render, get_object_or_404
from Shopping.forms import UserForm, UserFormIn, OrderForm, SearchForm
from .models import Product, Order, Category
from .serializers import ProductSerializer, OrderSerializer, CategorySerializer
from rest_framework import generics
from .serializers import UserSerializer
from rest_framework import permissions
from .permissions import IsOwnerOrReadOnly
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View


class ApiSearchProduct(generics.ListAPIView): #search on title of the products
    permission_classes = []
    def get(self, request):
        query = request.data
        if not 'title' in query:
            return Response('No Data entry')
        else:
            queryset = Product.objects.filter(title__contains=query['title'])
            serializer_class = ProductSerializer(queryset, many=True)
            return Response(serializer_class.data)


class ApiCatProductList(generics.ListAPIView):# returns the products of searched category
    permission_classes = []
    def get(self, request):
        query = request.data
        if not 'cat' in query:
            return Response('No Data entry')
        else:
            queryset = Product.objects.filter(cat__title__contains=query['cat'],)
            serializer_class = ProductSerializer(queryset, many=True)
            return Response(serializer_class.data)


class ApiCategoryList(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = []


class ApiSignUpView(APIView):
    permission_classes = []

    def post(self, request, format='json'):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            user = serializer.save()
            if user:
                token, created = Token.objects.get_or_create(user=user)
                json = serializer.data
                # todo bug in here. read about get_or_create to fix it
                json['token'] = token.key

                return Response(json, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ApiMyOrderList(generics.ListCreateAPIView):
    serializer_class = OrderSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)

    def get_queryset(self):
        return Order.objects.filter(person=self.request.user)

    def perform_create(self, serializer):

        serializer.person = self.request.user
        serializer.status = "P"
        super().perform_create(serializer,)


class ApiProductList(generics.ListCreateAPIView):
    """
    get:
    list of available products
    """
    queryset = Product.objects.filter(available__gt=0)
    serializer_class = ProductSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


def Index (request):
    return render(request, 'shopping/Index.html')


class ProductList(View):

    def get(self, request, pk):
        if pk == '0':
            all_products = Product.objects.all()
            return render (request, 'shopping/product.html', {'products': all_products})

        elif pk!=0:
            all_products = Product.objects.filter(cat_id = pk)
            cat = get_object_or_404(Category, pk=pk)
            return render(request, 'shopping/product.html', {'products': all_products, 'catcat':cat.title})


def ProductListDetail(request, pk):
    product = get_object_or_404( Product,pk = pk)
    return render(request, 'shopping/productdetail.html', {'product':product})


def CategoryDetail(request, pk):
    cat = get_object_or_404(Category, pk = pk)
    print(cat)
    print (cat.title)
    product = Product.objects.filter(cat__title__contains = cat.title)
    print(product)
    return render(request, 'shopping/categorydetail.html',{'product':product})


class SignUp (View): # TODO password check
    form_class = UserForm
    template_name = 'shopping/signup.html'

    # dispaly new form for register
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # just store it normally
            # clean and normalize data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user.set_password(password)

            user.save()

            # return user objects if credentials are correct
            user = authenticate(username=username, password=password,
                                first_name=first_name, last_name=last_name, email=email)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('shop:homepage')
        return render(request, self.template_name, {'form': form})


class SignIn (View):
    form_class = UserFormIn
    template_name = 'shopping/signin.html'

    # dispaly new form for register
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            # clean and normalize data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # return user objects if credentials are correct
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('shop:homepage')
        return render(request, self.template_name, {'form': form})


class search (View):
    form_class = SearchForm
    template_name = 'shopping/search.html'

    def get (self, request):
        products = []
        form = self.form_class(None)
        return render (request, self.template_name, { 'form' : form, 'products':products })

    def post (self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            category_title = form.cleaned_data['category_title']
            product_title = form.cleaned_data['product_title']
            if product_title:
                products = Product.objects.filter(title__contains=product_title)
            elif category_title:
                products = Product.objects.filter(cat__title__contains= category_title)
            elif category_title and product_title:
                pass
        return render (request, self.template_name, {'form':form, 'products':products})


def LogOut(request):
    logout(request)
    return render(request, 'shopping/Index.html')


def Categories (request):
    cats = Category.objects.all()
    return render (request, 'shopping/Categories.html', {'cats':cats})


class Orders(View):
    form_class = OrderForm
    template_name = 'shopping/myorders.html'
    def get(self, request):
        form = self.form_class(None)
        orders = Order.objects.filter(person=request.user)
        return render (request, self.template_name, {'orders':orders, 'form':form})

    def post (self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            # clean and normalize data
            products = form.cleaned_data['products']
            order = Order.objects.create(person = request.user)
            order.total_price = 0
            print(products)
            for p in products:
                order.products.add(p)
                order.total_price = order.total_price + p.price
            order.save()
            orders = Order.objects.filter(person=request.user)

        return render(request, self.template_name, {'orders':orders ,'form': form})

templates/shopping/Categories.html
{% extends 'shopping/base.html' %}
{% block body %}
    {% if cats %}
        <h1>{{ allcat }}</h1>
        <ul>
            {% for cat in cats %}
            <li>
                <a href="{% url 'shop:productlist' cat.id%}" >{{ cat.title }}</a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>{{ NoCat }}</h3>
    {% endif %}
{% endblock %}

templates/shopping/Index.html
{% extends 'shopping/base.html' %}
{% block body %}
<div style="font-size: 50px; font-family: 'Satisfy', cursive;"  id="middle" >
    <p >{{ WelcomeBanner }}</p>
    <a href="{% url 'shop:productlist' 0  %}" >{{ LetShop }}</a>
</div>
{% endblock %}

templates/shopping/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Maver!ck{% endblock %}</title>
    <!-- load the path to your static files -->
    {% load i18n %}
    {% load staticfiles %}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
          crossorigin="anonymous">


    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'Shopping/style.css' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
            integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
            crossorigin="anonymous"></script>
</head>
<body>
{% trans 'Welcome ' as Welcome %}
        {% trans 'Sign In' as SignIn %}
        {% trans 'My Orders' as MyOrders %}
        {% trans 'Logout' as Logout %}
        {% trans 'Sign Up' as SignUp %}
        {% trans 'Categories' as Categories %}
        {% trans 'Category' as Category %}
        {% trans 'search' as search %}
        {% trans 'Register' as Register %}
        {% trans 'Here is all Categories' as allcat %}
        {% trans 'There is no Category' as NoCat %}
        {% trans 'Welcome to Maverick Store' as WelcomeBanner %}
        {% trans 'Lets Shop' as LetShop %}
        {% trans 'Price' as price %}
        {% trans 'Available' as available %}
        {% trans 'Ordered Person' as OrderedPerson %}
        {% trans 'Date' as Date %}
        {% trans 'Status' as status %}
        {% trans 'Total Price' as total_price %}


<nav class="navbar navbar-expand-sm navbar-light bg-faded navbar-dark bg-dark">
    <div class="container-fluid">
        <!-- header -->
        <div class="navbar-brand">
            <button type="button" class="navbar-toggler" data-toggle="collapse"
                    data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">MaveR!cKk Store</a>
        </div>

        <!--- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class=" navbar navbar-nav">
                <li class="nav-item  navmiddle">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link  navmiddle" style="height: 50%" href="{% url 'shop:homepage' %}">
                            {{ Welcome }}
                            {{ request.user.username }}</a>
                    {% else %}<a class="nav-link  navmiddle" href="{% url 'shop:signin' %}">{{ SignIn }}</a>
                    {% endif %}
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item  navmiddle">
                        <a class="nav-link navmiddle"  href="{% url 'shop:myorders' %}">{{ MyOrders }}</a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link  navmiddle" href="{% url 'shop:logout' %}">{{ Logout }}</a>
                    {% else %}<a class="nav-link  navmiddle" href="{% url 'shop:signup' %}">{{ SignUp }}</a>
                    {% endif %}
                </li>
                <li><a class="nav-link  navmiddle" href="{% url 'shop:categories' %}">{{ Categories }}</a></li>
            </ul>

        <div class="search-box collapse navbar-collapse justify-content-end" id="navbarCollapse">
  <ul class="navbar-nav ">
    <li class="nav-item search-box">
      <a class="nav-link" href="{% url 'shop:search' %}"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;{{ search }}</a>
    </li>
  </ul>
</div>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

templates/shopping/categorydetail.html

{% extends 'shopping/base.html' %}
{% block title %}{{ product.title }} {% endblock %}
{% block body %}
    {% for p in product%}
    <p> {{ p.cat }}: {{ p.title }} </p>
    {% endfor %}
{% endblock %}


templates/shopping/form-template.html
{% for field in form %}
    <div class="form-group" style="color: black;"> 
        <div class="col-sm-offset-4 col-sm-10" >
            <span class="text small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/shopping/myorders.html
{% extends 'shopping/base.html' %}
{% block title %}My Orders{% endblock %}
{% load staticfiles %}
{% block body %}

    {% for order in orders %}
        <div class="col-md-8 offset-md-2 row order-container ">
            <div class=" col-md-6 ">
                <p style="background: whitesmoke"> {{ Date }}: {{ order.date }}</p>
            </div>
            <div class=" col-md-6">
                <p> {{ OrderedPerson }}: {{ order.person.username }}</p>
            </div>
            <div class="col-md-8 offset-md-0" >
                {% for p in order.products.all %}
                    <li> <a href="{% url 'shop:productdetail' p.id %}"> {{ p.title }}</a>: {{ p.price }} </li>
                {% endfor %}
            </div>
            <div class="col-md-6" >
                <div > {{ total_price }}: {{ order.total_price }}</div>
            </div>
            <div class="col-md-6" >
                <p> {{ status }}: {{ order.get_status_display }}</p>
            </div>
        </div>
    {% endfor %}

    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'shopping/form-template.html' %}
        <div class="form-inline">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>


{% endblock %}


templates/shopping/product.html
{% extends 'shopping/base.html' %}
{% load i18n %}

{% block body %}
    {% trans 'Here is all products' as allpro %}
    {% trans 'You dont have any products' as donthavepro %}
    {% load staticfiles %}

    {% if products %}
        <h1 class="text-center alert alert-dark col-md-10 offset-md-1">
        {% if catcat %}
            {{ catcat }}
        {% endif %}
            {{ allpro }}

        </h1>

        <div class="col-md-12 row products-container">
            {% for product in products %}
                <div class="col-md-3 product-parent-container">
                        <div class="col-md-12 product-container">
                        <a href="{% url 'shop:productdetail' product.id %}">
                            <div class="image-container">
                                {% if product.pic %}
                                    <img class="col-md-12 row" src="{{ product.pic.url }}">
                                {% else %}
                                    <img class="col-md-12 row" src="{% static 'Shopping/red_apple.jpg' %}">
                                {% endif %}
                            </div>
                            <p class="alert alert-light text-center col-md-12">{{ product.title }}</p>
                         </a>
                            <p class="text-center col-md-12">{{ price }}: <b>{{ product.price }}</b></p>
                        </div>

                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>{{ donthavepro }}</h3>
    {% endif %}
    <script>
        $(document).ready(function () {
            $('.image-container').height($('.image-container').width());
        });
    </script>
{% endblock %}

templates/shopping/productdetail.html
{% extends 'shopping/base.html' %}
{% load staticfiles %}
{% block title %}{{ product.title }} {% endblock %}
{% block body %}
    <div class="container">
    <div class="row ">

        <div class="col-8">
            <p class="alert alert-light text-center col-md-12">{{ product.title }}</p>
            <p class="alert alert-light text-center col-md-12">{{ Category }}: {{ product.cat }}</p>
            <p class="alert alert-light text-center col-md-12">{{ available }} {{ product.available }}</p>
            <p class="text-center col-md-12">{{ price }}: <b>{{ product.price }}</b></p>
        </div>

        <div class="col-4  product-container">
            {% if product.pic %}
                <img class="col-md-12 " src="{{ product.pic.url }}">
            {% else %}
                <img class="col-md-12 " src="{% static 'Shopping/red_apple.jpg' %}">
            {% endif %}
        </div>

    </div>
    {##}
    {#    <div class="col-md-12  products-container">#}
    {#        <div class="col-md-4 offset-md-4">#}
    {#            <div class="col-md-12 product-container">#}
    {#                {% if product.pic %}#}
    {#                    <img class="col-md-12" src="{{ product.pic.url }}">#}
    {#                {% else %}#}
    {#                    <img class="col-md-12" src="{% static 'Shopping/red_apple.jpg' %}">#}
    {#                {% endif %}#}
    {#                <p class="alert alert-light text-center col-md-12">{{ product.title }}</p>#}
    {#                <p class="alert alert-light text-center col-md-12">{{ Category }}: {{ product.cat }}</p>#}
    {#                <p class="alert alert-light text-center col-md-12">{{ available }} {{ product.available }}</p>#}
    {#                <p class="text-center col-md-12">{{ price }}: <b>{{ product.price }}</b></p>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}

{% endblock %}


templates/shopping/search.html
{% extends 'shopping/base.html' %}
{% block title  %}Search{% endblock %}

{% block body %}
<ul>
{% if products %}
    {% for p in products %}
      <li>  <p>{{ p.title}}: {{ p.cat.title}}</p></li>
    {% endfor %}
{% endif %}
</ul>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 com-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'shopping/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">{{ search }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/shopping/signin.html
{% extends 'shopping/base.html' %}
{% block title  %}{{ Register }}{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 com-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'shopping/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">{{ SignIn }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}





templates/shopping/signup.html
{% extends 'shopping/base.html' %}
{% block title  %}Register{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 com-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h1 style="color: black;">Create a New acount</h1>
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'shopping/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



